# Generated by Django 5.0 on 2023-12-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='quantity_sold',
        ),
    ]
