# Generated by Django 5.0 on 2023-12-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_amount_sale_quantity_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='quantity_sold',
            new_name='quantity',
        ),
    ]
