# Generated by Django 5.0 on 2023-12-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_expences_add_to_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='expences',
            name='price_per_unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expences',
            name='selling_price_per_unit',
            field=models.IntegerField(default=0),
        ),
    ]
