# Generated by Django 5.0 on 2023-12-26 21:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_stock_id_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2778e094-a6bb-477c-a801-fbdef51711b3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
