# Generated by Django 5.0 on 2023-12-26 21:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2693898e-7db1-4054-9604-927cf4355fea'), editable=False, primary_key=True, serialize=False),
        ),
    ]
