# Generated by Django 5.0 on 2023-12-26 21:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('569e1dcc-5c61-47b0-afeb-33e6b3157dce'), editable=False, primary_key=True, serialize=False),
        ),
    ]
