# Generated by Django 5.0 on 2023-12-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_sale_quantity_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='amount',
            new_name='quantity_sold',
        ),
    ]
