# Generated by Django 5.0 on 2023-12-25 20:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_expences_price_per_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=1)),
                ('price_per_unit', models.IntegerField(default=0)),
                ('selling_price_per_unit', models.IntegerField(default=0)),
                ('add_to_stock', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sale',
            name='item',
        ),
        migrations.DeleteModel(
            name='Expences',
        ),
    ]
