# Generated by Django 5.0 on 2023-12-25 20:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_expence_remove_sale_item_delete_expences'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6d1ca64b-4490-4f4a-9b27-150abde63559'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
