# Generated by Django 5.0 on 2023-12-26 04:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_stock_id_alter_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('419e1d12-a300-4ba4-815f-e6aff2d7a7b7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('name', 'price_per_unit')},
        ),
    ]
