# Generated by Django 5.0 on 2023-12-26 21:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('492f2cf7-e7b1-4755-8fc7-af14a17ba2f4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
