# Generated by Django 5.0 on 2023-12-26 21:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e3fe1fcb-5949-41f0-b604-c845b54032ee'), editable=False, primary_key=True, serialize=False),
        ),
    ]
