# Generated by Django 5.0 on 2023-12-26 21:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5a344744-7dac-4d6f-a36d-ea6440dcd413'), editable=False, primary_key=True, serialize=False),
        ),
    ]
