# Generated by Django 5.0 on 2023-12-26 21:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('165ae87b-32ac-4b1b-a10f-94f446b0252c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
