# Generated by Django 5.0 on 2024-02-07 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_stock_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_stock', to='main.stock'),
        ),
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='low_stock_threshold',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94f05cbf-06cb-4a43-a9c7-60352ad27726'), editable=False, primary_key=True, serialize=False),
        ),
    ]
