# Generated by Django 5.0 on 2024-02-15 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_category_alter_sale_total_alter_stock_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b5932c94-00b6-4d7a-8802-73156617423c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
