# Generated by Django 5.0 on 2024-02-15 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_sale_id_alter_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dc7f1019-3b41-47e0-81a2-829db38f507b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
