# Generated by Django 5.0 on 2024-02-15 13:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_sale_id_alter_stock_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f98e9fb-f656-44b8-9612-5462975712e3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
