# Generated by Django 5.0 on 2024-02-16 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_sale_id_alter_stock_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('NULL', 'Null'), ('CASH', 'Cash'), ('TRANSFER', 'Transfer'), ('CARD', 'Card')], default='Null', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='sold_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='use_amount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='use_quantity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('DEBT', 'Debt')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('19f37842-3aaa-4a06-a955-5a52a674c39e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
