# Generated by Django 5.0 on 2024-02-16 19:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_sale_payment_method_sale_sold_by_stock_is_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Transfer'), ('CARD', 'Card')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('38dc6371-bd51-4898-b440-2e005057a036'), editable=False, primary_key=True, serialize=False),
        ),
    ]
