# Generated by Django 5.0 on 2024-02-16 20:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_sale_payment_method_alter_stock_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='change',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b545435b-5449-4d08-8650-6951fcb32139'), editable=False, primary_key=True, serialize=False),
        ),
    ]
