# Generated by Django 5.0 on 2024-03-14 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_stock_unique_together_alter_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expence',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expences_stock', to='main.stock'),
        ),
    ]
