# Generated by Django 5.0 on 2024-03-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_expence_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='expence',
            name='total',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
