# Generated by Django 5.0 on 2024-03-14 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_expence_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
