# Generated by Django 5.0 on 2024-03-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_expence_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
